name: Run Frontend Tests

on:
  push:
    branches: [feature/Musa]
  pull_request:
    branches: [feature/Musa]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: FrontEnd/research-nexus

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Run test coverage
        run: npm run test:coverage

    

        
